### ISSUE TITLE
tsc fails: @types/markdown-it@14 conflicts with markdown-it 15's bundled types

### ISSUE THREAD

**Issue by paulchiu** [paulchiu/poe-editor#607]
## Summary

`tsc` fails on `main` after #601 bumped markdown-it to 15.0.1:

```
src/utils/markdownRenderers.ts(254,59): error TS2345:
  Argument of type '(state: MarkdownItBlockRuleState, ...) => boolean' is not assignable to
  parameter of type '(args_0: StateBlock, ...) => boolean'.
    Types of property 'attrs' are incompatible.
      Type 'TokenAttribute[] | null' is not assignable to type '[string, string][] | null'.
```

## Cause

markdown-it 15 ships its own bundled type declarations (`dist/markdown-it.d.mts`), so the separately installed `@types/markdown-it@14.2.0` is now both redundant and wrong. Two things in `markdownRenderers.ts` still depend on the old shapes:

- `import type Token from 'markdown-it/lib/token.mjs'` — markdown-it 15's `exports` map only exposes `.`, `./browser`, and `./package.json`. That subpath resolves solely through the stale `@types` package.
- Hand-rolled `MarkdownItInlineRuleState` / `MarkdownItBlockRuleState` interfaces that stand in for what markdown-it now exports directly as `StateInline` and `StateBlock`. `Token.attrs` changed from `[string, string][]` to `TokenAttribute[]`, so the hand-rolled shapes no longer structurally match.

## Why CI did not catch it

The `CI` workflow runs lint, format check, and unit tests. It runs neither `npm run tsc` nor `npm run build`, so a type error on `main` passes all required checks. Same blind spot as #606.

## Fix

Drop `@types/markdown-it` and use the types markdown-it 15 exports (`StateBlock`, `StateInline`, `Token`) in place of the hand-rolled interfaces.
